### ISSUE TITLE
NoSuchFile exception when using jar

### ISSUE THREAD

**Issue by Vladlis** [attatrol/ahsm#2]
This is what i've got when tried to use jar file:
```
vlad@vlad-N61PC-M2S ~ $ java -jar ahsm.jar checkstyle /home/vlad/site_after /home/vlad/site_before /home/vlad/site_result
java.nio.file.NoSuchFileException: /home/vlad/resources/maven-theme.css
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at attatrol.ahsm.FilesystemUtils.copyFile(FilesystemUtils.java:71)
	at attatrol.ahsm.site.InitialSiteVerifier.copyImmutableSiteFiles(InitialSiteVerifier.java:75)
	at attatrol.ahsm.Main.copyImmutables(Main.java:184)
	at attatrol.ahsm.Main.preparationStage(Main.java:121)
	at attatrol.ahsm.Main.main(Main.java:85)
Failed to copy files from first site, trying with second
java.nio.file.NoSuchFileException: /home/vlad/resources/maven-theme.css
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at attatrol.ahsm.FilesystemUtils.copyFile(FilesystemUtils.java:71)
	at attatrol.ahsm.site.InitialSiteVerifier.copyImmutableSiteFiles(InitialSiteVerifier.java:75)
	at attatrol.ahsm.Main.copyImmutables(Main.java:191)
	at attatrol.ahsm.Main.preparationStage(Main.java:121)
	at attatrol.ahsm.Main.main(Main.java:85)
This program creates symmetric difference from two maven site reports
generated for checkstyle build.
It has 3 obligatory command line arguments:
First one is the project name,
two next are the links to sites, already generated by maven-site-plugin,
forth argument is a destination for the result site, it is facultative, if skipped, you will find the result site in your home directory.
Any other arguments will be skipped.Failed to pass initial integrity testing.
```
I guess, the problem is in ```System.getProperty("user.dir")```
https://github.com/attatrol/ahsm/blob/master/src/attatrol/ahsm/site/InitialSiteVerifier.java#L76
as it used the directory where I was running the tool.

**Comment by attatrol** [comment]
@Vladlis 
I missed to add css resource to classpath, now this is done.
I exported the program as runnable jar from eclipse and tested it with success on Fedora 23.

Please confirm the issue is solved.

**Comment by Vladlis** [comment]
@attatrol
Thanks! Works good.
